addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - ninja-build
    - libglfw3-dev
    - libopenal-dev
    - libvulkan-dev

matrix:
  # The commented-out jobs are currently handled on Circle CI
  include:
  - language: android
    os: linux
    # Setting xenial here will cause it to use 12.04, with GCC 4.6 and other
    # prehistoric nightmares. So staying with 14.04 for the time being.
    dist: trusty
    env:
    - JOBID=android-vulkan
    - TARGET=android-vulkan
    addons:
      apt:
        packages:
        - ninja-build
    android:
      components:
      # Android API level 24 is the first with Vulkan support, but the crap
      # emulator doesn't even start, so it's useless. See
      # travis-android-vulkan.sh for how it's done instead.
      - build-tools-22.0.1
      - android-22
      - sys-img-armeabi-v7a-android-22

install:
- if [ "$BUILD_DEPRECATED" != "OFF" ]; then export BUILD_DEPRECATED=ON; fi
- if [ "$BUILD_STATIC" != "ON" ]; then export BUILD_STATIC=OFF; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TARGET" == "android-vulkan" ]; then wget -nc https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip && unzip -q android-*.zip; fi
# Download CMake 3.4.3 to ensure we're still compatible with it (Travis has
# 3.9 since December 2017). Also, the PATH setting can't be cached, so it's
# separate (bit me two times already). Android needs CMake 3.7, but
# https://gitlab.kitware.com/cmake/cmake/issues/17253 is fixed in 3.9.2, so
# grab that. FindVulkan is since 3.7, in that case just use the system package.
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TARGET" == "android-vulkan" ] && [ ! -e "$HOME/cmake/bin" ]; then cd $HOME ; wget -nc --no-check-certificate https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.tar.gz && mkdir -p cmake && cd cmake && tar --strip-components=1 -xzf ../cmake-3.9.2-Linux-x86_64.tar.gz && cd $TRAVIS_BUILD_DIR ; fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TARGET" == "android-vulkan" ]; then ./travis_android_vulkan.sh; fi
# Travis somehow is not able to gather all output, try to force it using this
- sync