dist: focal

addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libglfw3-dev
    - libopenal-dev
    - libvulkan-dev

matrix:
  fast_finish: true
  include:
  - language: android
    os: linux
    env:
    - JOBID=android-vulkan
    - TARGET=android-vulkan
    compiler: clang++-9
    addons:
      apt:
        sources:
        - sourceline: 'deb https://packagecloud.io/github/git-lfs/ubuntu/ focal main'
          key_url: 'https://packagecloud.io/github/git-lfs/gpgkey'
        - sourceline: 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-9 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages: 
        - clang-9
        - libllvm9
    android:
      components:
      # Android API level 24 is the first with Vulkan support, but the crap
      # emulator doesn't even start, so it's useless.
      - build-tools-22.0.1
      - android-22
      - sys-img-armeabi-v7a-android-22

cache:
  apt: true
  directories:
    - $HOME/.cache/cmake-3.16.3

install:
- wget -nc https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip 
- unzip -q android-*.zip

- wget -O cmake.sh https://cmake.org/files/v3.16/cmake-3.16.3-Linux-x86_64.sh
- mkdir -p $HOME/.cache/cmake-3.16.3
- sh cmake.sh --skip-license --exclude-subdir --prefix=$HOME/.cache/cmake-3.16.3
- rm cmake.sh
- sudo ln -sf $HOME/.cache/cmake-3.16.3/bin/cmake /usr/bin/cmake

before_script:
  - cmake --version

script:
# Generate debug keystore for APK signing
- keytool -genkeypair -keystore $HOME/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -validity 10000 -dname CN=,OU=,O=,L=,S=,C=

# *Native* Vulkan requires Android 24, build-tools-25.0.2, android-24 and
# sys-img-armeabi-v7a-android-24 in android.components in the YML, but the
# fucking emulator never starts, which means we can't test shit:
# https://github.com/googlemaps/android-maps-utils/issues/371
# So don't even bother there, use some ass-old version that works, and link to
# our own library, which is the fastest Vulkan implementation IN THE WORLD.
- $TRAVIS_BUILD_DIR/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi --gcc-toolchain=$TRAVIS_BUILD_DIR/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=$TRAVIS_BUILD_DIR/android-ndk-r16b/platforms/android-22/arch-arm  -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=22 -fexceptions -frtti -O3 -DNDEBUG  -Wl,--fix-cortex-a8  -fPIE -pie -Wl,--gc-sections -Wl,-z,nocopyreloc ci/libvulkan.cpp -std=c++11 -c -o vulkan.o
- $TRAVIS_BUILD_DIR/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ar rcs $HOME/libvulkan.a vulkan.o
- $TRAVIS_BUILD_DIR/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/arm-linux-androideabi/bin/ranlib $HOME/libvulkan.a

# Crosscompile
- mkdir build-android-arm && cd build-android-arm
- |
  CXX=clang++-9 cmake .. \
    -DANDROID_SDK=/usr/local/android-sdk \
    -DCMAKE_ANDROID_NDK=$TRAVIS_BUILD_DIR/android-ndk-r16b \
    -DCMAKE_SYSTEM_NAME=Android \
    -DCMAKE_SYSTEM_VERSION=22 \
    -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
    -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
    -DCMAKE_ANDROID_STL_TYPE=c++_static \
    -DVulkan_LIBRARY=$HOME/libvulkan.a \
    -DCMAKE_INSTALL_PREFIX=$HOME/deps \
    -DCMAKE_PREFIX_PATH=$HOME/deps \
    -DCMAKE_FIND_ROOT_PATH=$HOME/deps \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=ON \
    -DBUILD_DOCS=ON \
    -DINSTALL_APPS=ON
- cmake --build . --config Release

# Start simulator and run tests
- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- ctest --timeout 10 -C Release -j4

# Test install, after running the tests as for them it shouldn't be needed
- cmake --install . 

# Travis somehow is not able to gather all output, try to force it using this
- sync